"""Attendance correction message template generation.

All messages are polite, factual, and non-accusatory.
They request a review of a possible discrepancy — never demand a correction.
"""

from datetime import date
from typing import Optional


def generate_correction_subject(
    subject_code: str,
    subject_name: str,
    target_date: date,
) -> str:
    """Generate a polite email subject line for an attendance correction request.

    Args:
        subject_code: Academic subject code (e.g. "CS101").
        subject_name: Human-readable subject name (e.g. "Python Programming").
        target_date: The date of the attendance discrepancy.

    Returns:
        A concise, non-accusatory subject line.
    """
    formatted_date = target_date.strftime("%d %B %Y")
    return (
        f"Attendance Review Request – {subject_code} ({subject_name}) – {formatted_date}"
    )


def generate_correction_body(
    subject_code: str,
    subject_name: str,
    target_date: date,
    professor_name: str,
    student_name: Optional[str] = None,
) -> str:
    """Generate a polite, factual attendance correction request message body.

    The message:
    - Uses respectful, professional language
    - States the discrepancy factually
    - Requests a review (not a correction)
    - Never accuses the professor of an error
    - Includes all relevant details for verification

    Args:
        subject_code: Academic subject code.
        subject_name: Human-readable subject name.
        target_date: The date of the discrepancy.
        professor_name: Name of the professor.
        student_name: Optional student name; defaults to "the student" if omitted.

    Returns:
        A multi-line polite message body.
    """
    formatted_date = target_date.strftime("%d %B %Y")
    student_ref = student_name if student_name else "the student"

    return (
        f"Dear {professor_name},\n"
        f"\n"
        f"I hope this message finds you well.\n"
        f"\n"
        f"I am writing to bring to your attention a possible attendance discrepancy "
        f"for the following class:\n"
        f"\n"
        f"  Subject : {subject_name} ({subject_code})\n"
        f"  Date    : {formatted_date}\n"
        f"\n"
        f"According to {student_ref}'s records, {student_ref} attended the above class "
        f"on the date mentioned. However, the college portal currently shows "
        f"an \"Absent\" status for this session.\n"
        f"\n"
        f"Could you kindly review the attendance record at your convenience? "
        f"If there has been an inadvertent error, I would greatly appreciate "
        f"a correction.\n"
        f"\n"
        f"Thank you very much for your time and understanding.\n"
        f"\n"
        f"Warm regards,\n"
        f"{student_ref}\n"
        f"\n"
        f"---\n"
        f"This message was generated by the Attendance Automation system. "
        f"If you believe you received this message in error, please disregard it.\n"
    )
